apiVersion: v1
kind: Pod
metadata:
  name: ngrok
spec:
  containers:
    - name: ngrok
      image: ngrok/ngrok:latest
      args: ["start", "--config", "/etc/ngrok/ngrok.yml", "--all", "--log", "stdout"]
      volumeMounts:
        - name: ngrok-config
          mountPath: /etc/ngrok
  volumes:
    - name: ngrok-config
      configMap:
        name: unified-ngrok-config
