apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngrok
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      containers:
      - name: ngrok
        image: wernight/ngrok:latest
        env:
        - name: NGROK_AUTH
          value: "2uBfSbOzvEbBqC33h54sWiBc2ZP_2dhgeGtASXJWb9vQ3Q53T" 
        - name: NGROK_REGION
          value: "us"  # or "eu", "ap", etc.
        ports:
        - containerPort: 4040
        command: ["ngrok"]
        args: ["http", "nginx-service:80"]

---

apiVersion: v1
kind: Service
metadata:
  name: ngrok-service
spec:
  selector:
    app: ngrok
  ports:
    - protocol: TCP
      port: 4040
      targetPort: 4040