apiVersion: v1
kind: ConfigMap
metadata:
  name: unified-ngrok-config
data:
  ngrok.yml: |
    version: 2
    authtoken: 2uBfSbOzvEbBqC33h54sWiBc2ZP_2dhgeGtASXJWb9vQ3Q53T
    tunnels:
      jenkins:
        proto: http
        addr: jenkins-service:80
      gitea:
        proto: http
        addr: gitea-service:3000
