apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase
  labels:
    app: supabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supabase
  template:
    metadata:
      labels:
        app: supabase
    spec:
      containers:
      - name: supabase
        image: supabase/postgres:latest
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: "your-strong-password-here"
        - name: POSTGRES_DB
          value: "supabase"
        volumeMounts:
        - name: supabase-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
      volumes:
      - name: supabase-data
        persistentVolumeClaim:
          claimName: supabase-data

---

apiVersion: v1
kind: Service
metadata:
  name: supabase-service
spec:
  selector:
    app: supabase
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: supabase-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi