apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-rest
spec:
  selector:
    matchLabels:
      app: supabase-rest
  template:
    metadata:
      labels:
        app: supabase-rest
    spec:
      containers:
        - name: rest
          image: postgrest/postgrest:v11.2.0
          env:
            - name: PGRST_DB_URI
              value: postgres://postgres:postgres@supabase-postgres:5432/postgres
            - name: PGRST_DB_ANON_ROLE
              value: anon
            - name: PGRST_JWT_SECRET
              value: super-secret-jwt
            - name: PGRST_DB_SCHEMAS
              value: public,auth
          ports:
            - containerPort: 3000 
