apiVersion: v1
kind: Service
metadata:
  name: supabase-rest
spec:
  type: NodePort
  selector:
    app: supabase-rest
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 32005
