apiVersion: v1
kind: Service
metadata:
  name: supabase-studio
spec:
  selector:
    app: supabase-studio
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32003
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-studio
spec:
  selector:
    matchLabels:
      app: supabase-studio
  template:
    metadata:
      labels:
        app: supabase-studio
    spec:
      containers:
        - name: studio
          image: supabase/studio:latest
          env:
            - name: SUPABASE_URL
              value: http://157.90.239.132:32005
            - name: SUPABASE_ANON_KEY
              value: super-secret-jwt
            - name: SU{ABASE_DB_SCHEMAS
              value: public,auth
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: supabase-studio
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32003
  selector:
    app: supabase-studio
