
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: supabase-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: supabase-postgres
spec:
  selector:
    app: supabase-postgres
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-postgres
spec:
  selector:
    matchLabels:
      app: supabase-postgres
  template:
    metadata:
      labels:
        app: supabase-postgres
    spec:
      containers:
        - name: postgres
          image: supabase/postgres:15.1.0.89
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: supabase-postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: supabase-rest
spec:
  selector:
    app: supabase-rest
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-rest
spec:
  selector:
    matchLabels:
      app: supabase-rest
  template:
    metadata:
      labels:
        app: supabase-rest
    spec:
      containers:
        - name: rest
          image: postgrest/postgrest:v11.2.0
          ports:
            - containerPort: 3000
          env:
            - name: PGRST_DB_URI
              value: postgres://postgres:postgres@supabase-postgres:5432/postgres
            - name: PGRST_DB_ANON_ROLE
              value: anon
            - name: PGRST_JWT_SECRET
              value: super-secret-jwt

---
apiVersion: v1
kind: Service
metadata:
  name: supabase-studio
spec:
  selector:
    app: supabase-studio
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32003

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-studio
spec:
  selector:
    matchLabels:
      app: supabase-studio
  template:
    metadata:
      labels:
        app: supabase-studio
    spec:
      containers:
        - name: studio
          image: supabase/studio:latest
          ports:
            - containerPort: 3000
          env:
            - name: SUPABASE_URL
              value: http://supabase-rest:3000
            - name: SUPABASE_ANON_KEY
              value: super-secret-jwt
